# Config for Air live reload

[config]
  root = "."
  tmp_dir = "tmp"

[build]
  cmd = "go build -o tmp/main ."
  bin = "tmp/main"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor", ".git"]

[color]
  main = "cyan"